import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class SearchTabBodyPopularWidget extends HookWidget {
  const SearchTabBodyPopularWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: const [
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
        Text("aaa"),
      ],
    );
  }
}
